title: Mico's Github
logo: /assets/img/logo.png
description: A collection of my github projects
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_user_page: false
  owner_url: https://github.com/micophilip
logo: /assets/img/logo.jpeg