remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: mico's github
description: A collection of github projects
show_downloads: false
repository: micophilip/micophilip.github.io
author: mico
social_links:
  - platform: medium
    url: https://micophilip.medium.com
    icon: 📰
  - platform: dev.to
    url: http://dev.to/micophilip
    icon: 💻
date_format: "%Y/%m/%-d"
show_excerpts: false