title: Mico's Github
logo: /assets/img/logo.png
description: A collection of my github projects
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_user_page: false
  is_project_page: true
  owner_url: https://github.com/micophilip
  owner_name: micophilip
logo: /assets/img/logo.jpeg
social_links:
  - name: medium
    logo: /assets/img/medium.svg
    url: https://micophilip.medium.com
  - name: dev.to
    logo: /assets/img/dev.svg
    url: https://dev.to/micophilip