title: mico.codes
description: Thoughts & Projects
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_user_page: false
  is_project_page: true
  owner_url: https://github.com/micophilip
  owner_name: micophilip
logo: /assets/img/logo.svg
social_links:
  - name: medium
    logo: /assets/img/medium.svg
    url: https://micophilip.medium.com
  - name: leetcode
    logo: /assets/img/leetcode.svg
    url: https://leetcode.com/micophilip/
timezone: 'Americas/Toronto'
show_source: false